# Generated by Django 4.1 on 2022-09-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_mood',
            field=models.IntegerField(default=0),
        ),
    ]
