# Generated by Django 4.1 on 2022-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_profile_avg_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
