# Generated by Django 4.1 on 2022-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_mood',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
