# Generated by Django 4.1 on 2022-08-31 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Great', 'Feeling great!'), ('Good', 'Feeling good'), ('Okay', 'Not the best, not the worst'), ('Bad', 'Feeling the blues'), ('Awful', 'Feeling dreadful')], default='Okay', max_length=50)),
                ('reason', models.TextField()),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
