# Generated by Django 4.1 on 2022-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0002_alter_moodentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
