# Generated by Django 4.1 on 2022-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0003_alter_moodentry_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('avg_mood', models.CharField(max_length=50)),
            ],
        ),
    ]
