# Generated by Django 4.1 on 2022-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0005_alter_monthlyreview_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreview',
            name='month',
            field=models.DateField(),
        ),
    ]
