# Generated by Django 4.1 on 2022-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0006_alter_monthlyreview_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreview',
            name='num_of_entries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
