# Generated by Django 4.1 on 2022-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0007_monthlyreview_num_of_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_group', models.DateField()),
                ('num_of_entries', models.PositiveIntegerField(default=0)),
                ('avg_mood', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyReview',
        ),
    ]
