# Generated by Django 4.1 on 2022-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0008_review_delete_monthlyreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[(5, 'Feeling great!'), (4, 'Feeling good'), (3, 'Not the best, not the worst'), (2, 'Feeling the blues'), (1, 'Feeling dreadful')], default=3, max_length=50),
        ),
    ]
