# Generated by Django 4.1 on 2022-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0013_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avg_mood',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
