# Generated by Django 4.1 on 2022-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0014_alter_review_avg_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avg_mood',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
