# Generated by Django 4.1 on 2022-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0016_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.PositiveIntegerField(choices=[(5, 'Feeling great!'), (4, 'Feeling good'), (3, 'Not the best, not the worst'), (2, 'Feeling the blues'), (1, 'Feeling dreadful')], default=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_mood',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
