# Generated by Django 4.1 on 2022-09-01 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0019_alter_review_avg_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
