# Generated by Django 4.1 on 2022-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0021_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avg_mood',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
