# Generated by Django 4.1 on 2022-09-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0023_alter_review_avg_mood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
