# Generated by Django 4.1 on 2022-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0024_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('num_of_entries', models.PositiveIntegerField(default=0)),
                ('avg_mood', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
