# Generated by Django 4.1 on 2022-09-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0026_delete_monthlysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_situation', models.CharField(choices=[('Myself', 'Myself'), ('Acquaintances', 'Acquaintances'), ('Friends', 'Friends'), ('Family', 'Family'), ('Partner', 'Partner')], default='Myself', max_length=50)),
                ('activity', models.CharField(choices=[('Sports', 'Playing sport(s)'), ('Exercise', 'Doing exercise'), ('Movies', 'Watching movies'), ('Reading', 'Reading'), ('Gaming', 'Playing video games'), ('Drawing', 'Drawing'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='moodentry',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mood_tracker_app.categories'),
        ),
    ]
