# Generated by Django 4.1 on 2022-09-07 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0029_alter_moodentry_social_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_date_per_user'),
        ),
    ]
