# Generated by Django 4.1 on 2022-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker_app', '0031_remove_moodentry_unique_date_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moodentry',
            name='unique_date_per_user',
        ),
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_date_per_user'),
        ),
    ]
